### ISSUE TITLE
I'd like support for an Arduino RP2040 Nano Connect - Is this an option?

### ISSUE THREAD

**Issue by 927465** [allthingstalk/arduino-wifi-sdk#2]
Is this library still being developed? I see the talk about ESP32 support from August 21.

**Comment by epiller** [comment]
Yes it is. Unfortunately, support for RP2040 isn't planned as it's not an internet connected device by default (with the exception being some boards with uBlox WiFi modules such as the Nano Connect), though this might change in the future.
