### ISSUE TITLE
The examples: "ControlLed.ino" and "ControlLedBuiltIn.ino" no longer work since February 20th, 2022. 

### ISSUE THREAD

**Issue by jansolarski** [allthingstalk/arduino-wifi-sdk#3]
Hi,
i noticed the following: 
The examples: "ControlLed.ino" and "ControlLedBuiltIn.ino" no longer work since February 20th, 2022. 
"device.setActuationCallback(asset, actuation);" no longer works. 
The "auction" is never called. 
Does somebody have the same problems? 
Sincerely
Jan Solarski

**Comment by epiller** [comment]
Hey @jansolarski, sorry about that. Our dev team is actively investigating this issue as it's not related to the SDK. It will be fixed very soon.

**Comment by epiller** [comment]
Hey @jansolarski, could you test it again? I experienced this issue as well but I'm pretty sure it has been resolved.

**Comment by jansolarski** [comment]
The examples: "ControlLed.ino" and "ControlLedBuiltIn.ino" work fine again.
The problem has been resolved.
